#set document(title: "Index lemmas for De Bruijn terms")
#set page(paper: "a4", margin: 2.2cm, numbering: "1")
#set text(size: 10.5pt)
#set par(justify: true)
#set heading(numbering: "1.")

#let definition(body) = block(inset: (left: 0.8em), stroke: (left: 0.5pt + gray))[*Definition.* #body]
#let proposition(name, body) = block(inset: (left: 0.8em), stroke: (left: 0.5pt + gray))[*#name.* #body]
#let proof(body) = [_Proof._ #body #h(1fr) $square$]
#let sh(d, c) = $scripts(arrow.t)^(#d)_(#c)$

#align(center)[
  #text(size: 15pt, weight: "bold")[Index lemmas for De Bruijn terms]

  type_theory `debruijn` design note
]

This note supports the `debruijn` design page. It fixes the definitions of
shifting, index substitution and beta reduction implemented by `shift`,
`substitute_bound` and `instantiate`, and proves the properties the page
relies on: composition and commutation of shifts, safety of the downward shift
in beta reduction, preservation of scope, and the substitution lemma.

= Definitions

Terms are generated by $t ::= v | x | i | t space u_1 dots u_n | lambda. t$ with
values $v$, free names $x$ and indices $i in NN$. Values and free names are
unaffected by every operation below; we omit their cases.

#definition[
  For $d in ZZ$ and $c in NN$, the shift $#sh($d$, $c$) t$ is
  $ #sh($d$, $c$) i = cases(i & "if" i < c, i + d & "if" i >= c), quad
    #sh($d$, $c$) (lambda. t) = lambda. #sh($d$, $c + 1$) t, quad
    #sh($d$, $c$) (t space macron(u)) = (#sh($d$, $c$) t) space (#sh($d$, $c$) macron(u)). $
  It is defined when no index crosses its cutoff: there is no index $i >= c$
  with $i + d < c$, where $c$ is the cutoff at that occurrence. Such an index
  would be captured by an enclosing binder (or become negative). For $d >= 0$
  the shift is always defined. The implementation carries the binder depth $k$
  instead of increasing $c$, tests $i >= c + k$, and reports the crossing
  $i + d < c + k$ as `NegativeShift`.
]

#definition[
  For $j in NN$, the index substitution $[j |-> s] t$ is
  $ [j |-> s] i = cases(s & "if" i = j, i & "otherwise"), quad
    [j |-> s] (lambda. t) = lambda. [j + 1 |-> #sh($1$, $0$) s] t, $
  and homomorphic on applications. The implementation replaces, under $k$
  binders, the index $j + k$ by $#sh($k$, $0$) s$.
]

#definition[
  Beta reduction is $(lambda. t) space s -> #sh($-1$, $0$) ([0 |-> #sh($1$, $0$) s] t)$.
  A term is _well scoped at depth $n$_ if every index under $k$ binders is
  smaller than $n + k$. We write $"fi"(t)$ for the set of free indices of $t$
  relative to its root: an index $i$ under $k$ binders contributes $i - k$
  when $i >= k$.
]

= Shifts

#proposition("Lemma 1 (identity and composition)")[
  $#sh($0$, $c$) t = t$, and for $a, b >= 0$,
  $#sh($a$, $c$) #sh($b$, $c$) t = #sh($a + b$, $c$) t$.
]

#proof[
  Induction on $t$. For an index $i$: if $i < c$ all three shifts leave it
  unchanged. If $i >= c$ then $#sh($0$, $c$) i = i$, and $i + b >= c$ because
  $b >= 0$, so $#sh($a$, $c$) #sh($b$, $c$) i = i + b + a = #sh($a + b$, $c$) i$.
  For $lambda. t$ both sides move to cutoff $c + 1$ and the induction
  hypothesis applies; applications are immediate.
]

#proposition("Lemma 2 (commutation)")[
  For $c <= c'$ and $d, d' >= 0$:
  $#sh($d$, $c$) #sh($d'$, $c'$) t = #sh($d'$, $c' + d$) #sh($d$, $c$) t$.
]

#proof[
  Induction on $t$; the binder case increases $c$ and $c'$ together and keeps
  $c <= c'$. For an index $i$ there are three cases.
  - $i < c$: both sides give $i$.
  - $c <= i < c'$: the left gives $#sh($d$, $c$) i = i + d$; the right gives
    $#sh($d'$, $c' + d$) (i + d) = i + d$ because $i + d < c' + d$.
  - $i >= c'$: the left gives $i + d' + d$; the right gives $i + d >= c' + d$
    and then $i + d + d'$.
]

#proposition("Lemma 3 (cancellation)")[
  $#sh($-1$, $c$) #sh($1$, $c$) t = t$, and the left-hand side is always defined.
]

#proof[
  An index $i < c$ is untouched. An index $i >= c$ becomes $i + 1 >= c + 1$,
  so the downward shift touches it and gives $i + 1 - 1 = i >= c$: no index
  crosses the cutoff. The binder case raises the cutoff on both sides.
]

= Substitution

#proposition("Lemma 4 (unfolding)")[
  $[j |-> s] t$ computed by the recursive definition equals the
  implementation's result: under $k$ binders, $j + k$ is replaced by
  $#sh($k$, $0$) s$.
]

#proof[
  After passing $k$ binders the recursive definition substitutes for index
  $j + k$ the term $#sh($1$, $0$) dots #sh($1$, $0$) s$ ($k$ shifts), which is
  $#sh($k$, $0$) s$ by Lemma 1.
]

#proposition("Lemma 5 (free indices of a substitution)")[
  If $t$ is well scoped at depth $n + 1$ and $s$ at depth $n$, then
  $"fi"([0 |-> #sh($1$, $0$) s] t) subset.eq {1, dots, n}$.
]

#proof[
  We prove the stronger statement for every $k >= 0$: if $t$ is well scoped at
  depth $k + n + 1$, then every free index of
  $u_k = [k |-> #sh($k + 1$, $0$) s] t$ lies in
  ${0, dots, k - 1} union {k + 1, dots, k + n}$.
  The case $k = 0$ is the lemma (using Lemma 4).

  Induction on $t$. If $t = i$ with $i = k$, then $u_k = #sh($k + 1$, $0$) s$,
  whose free indices are $j + k + 1$ for $j in "fi"(s) subset.eq {0, dots, n - 1}$,
  so they lie in ${k + 1, dots, k + n}$. If $i != k$, then $u_k = i$ with
  $i < k + n + 1$ and $i != k$, which is in the stated set. Applications are
  immediate. For $t = lambda. t'$, $u_k = lambda. u'_(k + 1)$ where $t'$ is well
  scoped at depth $(k + 1) + n + 1$ and, by Lemma 1,
  $#sh($1$, $0$) #sh($k + 1$, $0$) s = #sh($k + 2$, $0$) s$, so the induction
  hypothesis gives free indices of $u'_(k+1)$ in
  ${0, dots, k} union {k + 2, dots, k + 1 + n}$. Removing the binder removes $0$
  and subtracts one: ${0, dots, k - 1} union {k + 1, dots, k + n}$.
]

#proposition("Theorem 6 (safe instantiation, preservation of scope)")[
  If $lambda. t$ and $s$ are well scoped at depth $n$, then
  $#sh($-1$, $0$) ([0 |-> #sh($1$, $0$) s] t)$ is defined and well scoped at
  depth $n$. Consequently `instantiate` and `reduce_once` never return a
  `ScopeError` on well-scoped input, and every reduct of a well-scoped term is
  well scoped.
]

#proof[
  By Lemma 5 every free index of the substituted body lies in
  ${1, dots, n}$. Under $k$ binders the shift by $-1$ has cutoff $k$; it
  leaves the bound indices $i < k$ alone and touches the indices $i = k + m$
  with $m$ a free index, so $m >= 1$ and $i - 1 = k + (m - 1) >= k$. Hence no
  index crosses its cutoff, the shift is defined, the free indices are mapped
  into ${0, dots, n - 1}$, and the result is well scoped at depth $n$. A beta step in a context replaces a well-scoped subterm by a
  well-scoped subterm at the same depth, so scope is preserved globally.
]

#proposition("Lemma 7 (substitution lemma)")[
  For $i < j$ and terms $s, r$:
  $[j |-> r] ([i |-> s] t) = [i |-> [j |-> r] s] ([j |-> r] t)$
  whenever $i in.not "fi"(r)$.
]

#proof[
  Induction on $t$. For the index $i$: the left gives $[j |-> r] s$; the right
  leaves $i$ by $[j |-> r]$ (as $i != j$) and then gives $[j |-> r] s$. For the
  index $j$: the left leaves $j$ and gives $r$; the right gives $r$ and then
  $[i |-> dots] r = r$ because $i in.not "fi"(r)$. Other indices are untouched
  on both sides. Under a binder both indices increase by one and both
  replacements are shifted by $#sh($1$, $0$)$; the side condition is preserved
  because $"fi"(#sh($1$, $0$) r) = "fi"(r) + 1$, and $[j + 1 |-> #sh($1$, $0$) r] (#sh($1$, $0$) s) = #sh($1$, $0$) ([j |-> r] s)$
  by the shift–substitution commutation, which is proved the same way as
  Lemma 2.
]

= Relation to named syntax

Let $⌜t⌝$ be the translation `from_named`, and $⌜b⌝_x$ the translation of $b$
in which $x$ is the innermost binder.

#proposition("Theorem 8 (translation commutes with beta)")[
  $⌜b[x := a]⌝ = #sh($-1$, $0$) ([0 |-> #sh($1$, $0$) ⌜a⌝] ⌜b⌝_x)$, where
  $b[x := a]$ is capture-avoiding named substitution.
]

#proof[
  By induction on $b$, generalised to $k$ inner binders between the occurrence
  and $x$, as in Lemma 5. An occurrence of $x$ under $k$ inner binders has
  index $k$ in $⌜b⌝_x$ and receives $#sh($k + 1$, $0$) ⌜a⌝$, which after the
  final downward shift is $#sh($k$, $0$) ⌜a⌝$: the translation of $a$ placed
  under those $k$ binders, as the named substitution places $a$ under the same
  binders (renamed if needed, which the translation does not see). Another bound
  variable keeps its distance to its binder; after removing the binder of $x$,
  variables bound outside it are one binder closer, which is the downward
  shift. Free names are unchanged.
]
